version: '3.1'

services:

  db:
    image: mongo
    restart: always
    container_name: db
    ports:
       - 27017:27017
       - 28017:28017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  api:
    build: .
    restart: always
    ports:
      - 8080:8080
    links:
      - db
